const labCopy={
 ar:{all:'الكل',correct:'إجابة صحيحة',wrong:'مش أفضل إجابة',complete:'خلصت المجموعة 👏',completeText:'غيّر الفصل أو نوع التدريب عشان تكمل التحدي.',restart:'إعادة المجموعة',empty:'لا توجد أسئلة لهذا الفلتر حاليًا.',core:'CORE',applied:'APPLIED',treatment:'TREATMENT',modes:{mcq:'RAPID MCQ',case:'CLINICAL CASE',treatment:'TREATMENT CHALLENGE'},chapters:{all:'كل الفصول',introduction:'Introduction',bacterial:'Bacterial',fungal:'Fungal',viral:'Viral',parasitic:'Parasitic',mycobacterial:'Mycobacterial'},resultLabel:'تمت الإجابة'},
 en:{all:'All',correct:'Correct answer',wrong:'Not the best answer',complete:'Set completed 👏',completeText:'Change the chapter or practice mode to continue.',restart:'Restart set',empty:'No questions are available for this filter yet.',core:'CORE',applied:'APPLIED',treatment:'TREATMENT',modes:{mcq:'RAPID MCQ',case:'CLINICAL CASE',treatment:'TREATMENT CHALLENGE'},chapters:{all:'All chapters',introduction:'Introduction',bacterial:'Bacterial',fungal:'Fungal',viral:'Viral',parasitic:'Parasitic',mycobacterial:'Mycobacterial'},resultLabel:'answered'}
};

const questions={
 ar:[
  {id:'m1',mode:'mcq',chapter:'introduction',difficulty:'CORE',q:'الجلد يتكوّن تشريحيًا من كام طبقة رئيسية؟',options:['طبقتين','ثلاث طبقات','أربع طبقات','خمس طبقات'],answer:1,feedback:'Epidermis وDermis وHypodermis.',reasoning:'فهم الطبقات الثلاثة هو المدخل لفهم عمق العدوى ومكان الإصابة.'},
  {id:'m2',mode:'mcq',chapter:'bacterial',difficulty:'CORE',q:'أي وصف يرتبط بشكل كلاسيكي بـ non-bullous impetigo؟',options:['Silvery scales','Honey-colored crusts','Burrows بين الأصابع','Coral-red fluorescence'],answer:1,feedback:'القشور العسلية من أشهر مفاتيح التعرف على impetigo.',reasoning:'الـvesicles الهشة تنفجر مبكرًا وتترك erosions سطحية مغطاة بقشور صفراء عسلية.'},
  {id:'m3',mode:'mcq',chapter:'fungal',difficulty:'CORE',q:'ما أكثر dermatophyte شيوعًا في Tinea pedis حسب الفصل؟',options:['Trichophyton rubrum','Candida albicans','Malassezia furfur','Microsporum canis'],answer:0,feedback:'T. rubrum هو الأكثر شيوعًا.',reasoning:'الفصل يذكر T. rubrum كالمسبب الأكثر شيوعًا، مع T. interdigitale وE. floccosum كمسببات أخرى.'},
  {id:'m4',mode:'mcq',chapter:'viral',difficulty:'CORE',q:'بعد العدوى الأولية، أين يدخل HSV في مرحلة latency؟',options:['الكبد','العقد العصبية الحسية','النخاع العظمي','الغدد العرقية'],answer:1,feedback:'HSV يبقى كامنًا في sensory ganglia.',reasoning:'إعادة التنشيط تسمح للفيروس بالانتقال مرة أخرى إلى الجلد أو الأغشية المخاطية.'},
  {id:'m5',mode:'mcq',chapter:'parasitic',difficulty:'CORE',q:'أي عرض يدعم تشخيص scabies بقوة؟',options:['حكة ليلية شديدة','ألم عصبي في dermatome','قشور عسلية','فقدان الإحساس في patch'],answer:0,feedback:'الحكة الليلية الشديدة من العلامات المهمة في scabies.',reasoning:'الـburrows وتوزيع الإصابة في finger webs والرسغين مع الحكة الليلية يصنعون نمطًا مميزًا.'},
  {id:'m6',mode:'mcq',chapter:'mycobacterial',difficulty:'CORE',q:'أي خاصية تفسر فقدان الإحساس والتشوهات في leprosy؟',options:['غزو الأعصاب الطرفية','عدوى بصيلات الشعر فقط','إنتاج سموم مقشرة','انسداد الغدد الدهنية'],answer:0,feedback:'M. leprae لها ميل لإصابة الأعصاب الطرفية.',reasoning:'إصابة Schwann cells والأعصاب الطرفية تؤدي إلى sensory loss وقد تتطور إلى deformities إذا لم تُعالج.'},

  {id:'c1',mode:'case',chapter:'bacterial',difficulty:'APPLIED',vignette:'مريضة بدأت فجأة بحرارة مرتفعة، ومعها منطقة حمراء لامعة مرتفعة ذات حدود واضحة جدًا على الساق.',q:'ما التشخيص الأقرب؟',options:['Cellulitis','Erysipelas','Tinea corporis','Erythrasma'],answer:1,feedback:'الحدود المرتفعة الواضحة والبداية المفاجئة ترجح erysipelas.',reasoning:'Erysipelas أكثر سطحية وتنتشر عبر الأوعية الليمفاوية السطحية، بعكس cellulitis الأعمق وحدوده غير الواضحة.'},
  {id:'c2',mode:'case',chapter:'bacterial',difficulty:'APPLIED',vignette:'رجل لديه بقع بنية محمرة محددة في منطقة الثنيات مع fine scaling، وتظهر coral-red fluorescence تحت Wood’s lamp.',q:'ما التشخيص الأكثر احتمالًا؟',options:['Tinea cruris','Candidiasis','Erythrasma','Psoriasis'],answer:2,feedback:'Coral-red fluorescence علامة قوية على erythrasma.',reasoning:'Corynebacterium minutissimum ينتج porphyrins تعطي هذا اللون المميز تحت Wood’s lamp.'},
  {id:'c3',mode:'case',chapter:'fungal',difficulty:'APPLIED',vignette:'مريض لديه plaque حلقية حمراء متقشرة، الحافة نشطة والمركز أهدأ، على جلد غير مشعر.',q:'ما التشخيص الأقرب؟',options:['Tinea corporis','Impetigo','Herpes zoster','Erysipelas'],answer:0,feedback:'الـannular scaly plaque مع central clearing ترجح Tinea corporis.',reasoning:'Dermatophytes تصيب keratinized tissue، والمظهر الحلقي ذو الحافة النشطة من العلامات الكلاسيكية.'},
  {id:'c4',mode:'case',chapter:'viral',difficulty:'APPLIED',vignette:'طفل عمره 3 سنوات يعاني من حمى، التهاب ونزف باللثة، وvesicles مؤلمة متعددة داخل الفم تحولت إلى ulcers.',q:'ما الصورة السريرية الأقرب؟',options:['Primary herpetic gingivostomatitis','Hand-foot-mouth disease فقط','Impetigo','Oral candidiasis'],answer:0,feedback:'هذا نمط primary HSV-1 gingivostomatitis.',reasoning:'الفصل يصفها كأشهر عدوى HSV-1 أولية عرضية في الأطفال من 1–5 سنوات.'},
  {id:'c5',mode:'case',chapter:'parasitic',difficulty:'APPLIED',vignette:'أكثر من فرد في المنزل يعاني من حكة شديدة ليلًا. توجد papules وburrows بين الأصابع وعلى الرسغين.',q:'ما التشخيص والخطوة الوقائية الأهم؟',options:['Scabies وعلاج المخالطين','Tinea وعزل المريض فقط','HSV وإعطاء antiviral للجميع','Impetigo وعدم غسل الملابس'],answer:0,feedback:'Scabies مع علاج المخالطين وتنظيف الملابس والمفروشات.',reasoning:'الانتقال غالبًا بالاحتكاك الجلدي المطول؛ علاج المخالطين ضروري لتقليل reinfestation.'},
  {id:'c6',mode:'case',chapter:'mycobacterial',difficulty:'APPLIED',vignette:'مريض لديه patch ناقصة التصبغ مع نقص واضح في الإحساس، مع سماكة في عصب طرفي قريب.',q:'ما التشخيص الذي يجب التفكير فيه؟',options:['Leprosy','Pityriasis versicolor','Erythrasma','Contact dermatitis'],answer:0,feedback:'فقدان الإحساس مع إصابة الأعصاب الطرفية يرفع الاشتباه في leprosy.',reasoning:'Leprosy مرض مزمن يصيب الجلد والأعصاب الطرفية، وقد يؤدي إلى nerve damage وتشوهات إذا لم يُكتشف مبكرًا.'},

  {id:'t1',mode:'treatment',chapter:'bacterial',difficulty:'TREATMENT',vignette:'طفل لديه عدد محدود من lesions impetigo حول الفم بدون أعراض جهازية.',q:'ما أنسب اختيار مبدئي حسب مسار الفصل؟',options:['Topical mupirocin','IV vancomycin','Oral fluoroquinolone','لا علاج أو نظافة'],answer:0,feedback:'العلاج الموضعي هو الخط الأول في impetigo المحدودة.',reasoning:'الفصل يلخص أن limited impetigo تناسبها mupirocin موضعيًا، بينما extensive disease تحتاج علاجًا جهازيًا.'},
  {id:'t2',mode:'treatment',chapter:'bacterial',difficulty:'TREATMENT',vignette:'مريض لديه extensive impetigo بدون عوامل واضحة لـMRSA أو حساسية beta-lactam.',q:'أي اختيار جهازي مذكور كخيار شائع أولي؟',options:['Cephalexin','Acyclovir','Permethrin','Terbinafine'],answer:0,feedback:'Cephalexin من الخيارات الجهازية الأولى لـS. aureus وStrep.',reasoning:'اختيار المضاد يعتمد على الانتشار والمسبب المتوقع والمقاومة المحلية، مع تعديل المسار عند وجود MRSA أو حساسية.'},
  {id:'t3',mode:'treatment',chapter:'fungal',difficulty:'TREATMENT',vignette:'مريض بالغ لديه Tinea pedis موضعية غير معقدة بين الأصابع.',q:'ما العلاج المناسب كبداية؟',options:['Topical terbinafine أو clotrimazole','IV acyclovir','Oral rifampin منفردًا','Topical mupirocin فقط'],answer:0,feedback:'العلاج الموضعي المضاد للفطريات مناسب للحالة الموضعية.',reasoning:'الفصل يذكر terbinafine وclotrimazole وketoconazole موضعيًا عادة لمدة 2–4 أسابيع، مع العلاج الجهازي للحالات الشديدة أو المزمنة.'},
  {id:'t4',mode:'treatment',chapter:'viral',difficulty:'TREATMENT',vignette:'مريض لديه primary HSV-1 symptomatic infection، وبدأت الأعراض منذ أقل من 72 ساعة.',q:'أي مبدأ علاجي يعطي أفضل فرصة للاستجابة؟',options:['بدء antiviral مبكرًا','تأخير العلاج أسبوعين','استخدام مضاد فطري','استخدام permethrin'],answer:0,feedback:'بدء acyclovir أو بدائله مبكرًا يحسن الاستجابة.',reasoning:'الفصل يؤكد أن العلاج المضاد للفيروسات يكون أفضل عند البدء خلال أقل من 72 ساعة، مع IV acyclovir للحالات الشديدة أو المنتشرة.'},
  {id:'t5',mode:'treatment',chapter:'parasitic',difficulty:'TREATMENT',vignette:'مريض بالغ لديه classic scabies بدون تعقيدات أو immunosuppression.',q:'ما العلاج الأول المذكور في الفصل؟',options:['Permethrin 5% مع التكرار بعد 7 أيام','Topical acyclovir','Oral cephalexin فقط','Clofazimine منفردة'],answer:0,feedback:'Permethrin 5% هو العلاج الأول للحالة الكلاسيكية.',reasoning:'يُكرر العلاج عادة بعد 7 أيام، مع علاج المخالطين وغسل الملابس والمفروشات لتجنب إعادة العدوى.'},
  {id:'t6',mode:'treatment',chapter:'mycobacterial',difficulty:'TREATMENT',vignette:'تم تشخيص مريض بـmultibacillary leprosy.',q:'ما المبدأ العلاجي الأساسي؟',options:['Long-term multidrug therapy','مضاد حيوي موضعي لمدة 3 أيام','مضاد فيروسات منفرد','لا يحتاج علاج إذا لم توجد حمى'],answer:0,feedback:'Leprosy تحتاج علاجًا طويلًا متعدد الأدوية.',reasoning:'العلاج متعدد الأدوية يقلل المقاومة ويشمل أدوية مثل rifampin وdapsone وclofazimine حسب التصنيف والبروتوكول.'}
 ],
 en:[
  {id:'m1',mode:'mcq',chapter:'introduction',difficulty:'CORE',q:'How many major anatomical layers make up the skin?',options:['Two','Three','Four','Five'],answer:1,feedback:'Epidermis, dermis, and hypodermis.',reasoning:'Understanding these three layers is the foundation for reasoning about infection depth and site.'},
  {id:'m2',mode:'mcq',chapter:'bacterial',difficulty:'CORE',q:'Which description is classically associated with non-bullous impetigo?',options:['Silvery scales','Honey-colored crusts','Finger-web burrows','Coral-red fluorescence'],answer:1,feedback:'Honey-colored crusts are a classic clue for impetigo.',reasoning:'Fragile vesicles rupture early and leave superficial erosions covered by yellow honey-colored crusts.'},
  {id:'m3',mode:'mcq',chapter:'fungal',difficulty:'CORE',q:'Which dermatophyte is listed as the most common cause of tinea pedis?',options:['Trichophyton rubrum','Candida albicans','Malassezia furfur','Microsporum canis'],answer:0,feedback:'T. rubrum is the most common cause.',reasoning:'The chapter also lists T. interdigitale and E. floccosum as other causative fungi.'},
  {id:'m4',mode:'mcq',chapter:'viral',difficulty:'CORE',q:'Where does HSV establish latency after primary infection?',options:['Liver','Sensory ganglia','Bone marrow','Sweat glands'],answer:1,feedback:'HSV becomes latent in sensory ganglia.',reasoning:'Reactivation allows the virus to migrate back to the skin or mucosa and cause recurrent lesions.'},
  {id:'m5',mode:'mcq',chapter:'parasitic',difficulty:'CORE',q:'Which symptom strongly supports a diagnosis of scabies?',options:['Intense nocturnal itch','Dermatomal neuralgia','Honey-colored crusts','Sensory loss in a patch'],answer:0,feedback:'Intense nocturnal pruritus is an important scabies clue.',reasoning:'Burrows, finger-web or wrist involvement, and night itch create a characteristic clinical pattern.'},
  {id:'m6',mode:'mcq',chapter:'mycobacterial',difficulty:'CORE',q:'Which feature explains sensory loss and deformity in leprosy?',options:['Peripheral nerve invasion','Hair-follicle infection only','Exfoliative toxin production','Sebaceous gland obstruction'],answer:0,feedback:'M. leprae has a predilection for peripheral nerves.',reasoning:'Involvement of Schwann cells and peripheral nerves can cause sensory loss and later deformity.'},

  {id:'c1',mode:'case',chapter:'bacterial',difficulty:'APPLIED',vignette:'A patient develops abrupt high fever and a shiny, raised, bright-red leg lesion with a sharply defined border.',q:'What is the most likely diagnosis?',options:['Cellulitis','Erysipelas','Tinea corporis','Erythrasma'],answer:1,feedback:'The raised sharp border and abrupt onset favor erysipelas.',reasoning:'Erysipelas is more superficial, while cellulitis is deeper and usually has ill-defined margins.'},
  {id:'c2',mode:'case',chapter:'bacterial',difficulty:'APPLIED',vignette:'An adult has sharply demarcated reddish-brown flexural patches with fine scale and coral-red fluorescence under a Wood’s lamp.',q:'What is the most likely diagnosis?',options:['Tinea cruris','Candidiasis','Erythrasma','Psoriasis'],answer:2,feedback:'Coral-red fluorescence strongly supports erythrasma.',reasoning:'Corynebacterium minutissimum produces porphyrins responsible for this Wood’s lamp finding.'},
  {id:'c3',mode:'case',chapter:'fungal',difficulty:'APPLIED',vignette:'A patient has an annular erythematous scaly plaque with an active border and central clearing on smooth skin.',q:'What is the most likely diagnosis?',options:['Tinea corporis','Impetigo','Herpes zoster','Erysipelas'],answer:0,feedback:'An annular scaly plaque with central clearing favors tinea corporis.',reasoning:'Dermatophytes infect keratinized tissue, and the active ring-shaped border is a classic clue.'},
  {id:'c4',mode:'case',chapter:'viral',difficulty:'APPLIED',vignette:'A 3-year-old has fever, inflamed bleeding gums, and multiple painful oral vesicles that ulcerate.',q:'Which clinical presentation is most likely?',options:['Primary herpetic gingivostomatitis','Isolated hand-foot-mouth disease','Impetigo','Oral candidiasis'],answer:0,feedback:'This is the classic pattern of primary HSV-1 gingivostomatitis.',reasoning:'The chapter describes it as the most common symptomatic primary HSV-1 infection in children aged 1–5 years.'},
  {id:'c5',mode:'case',chapter:'parasitic',difficulty:'APPLIED',vignette:'Several household members have severe night itching with papules and burrows on the finger webs and wrists.',q:'What is the diagnosis and key preventive step?',options:['Scabies and treat close contacts','Tinea and isolate only the index patient','HSV and give antivirals to everyone','Impetigo and do not wash bedding'],answer:0,feedback:'Scabies requires treatment of close contacts and environmental measures.',reasoning:'Prolonged skin contact is the main route, so contact treatment helps prevent reinfestation.'},
  {id:'c6',mode:'case',chapter:'mycobacterial',difficulty:'APPLIED',vignette:'A patient has a hypopigmented patch with clear sensory loss and thickening of a nearby peripheral nerve.',q:'Which diagnosis should be considered?',options:['Leprosy','Pityriasis versicolor','Erythrasma','Contact dermatitis'],answer:0,feedback:'Sensory loss plus peripheral nerve involvement raises concern for leprosy.',reasoning:'Leprosy primarily affects skin and peripheral nerves and can lead to nerve damage if untreated.'},

  {id:'t1',mode:'treatment',chapter:'bacterial',difficulty:'TREATMENT',vignette:'A child has a small number of localized impetigo lesions around the mouth without systemic symptoms.',q:'What is the best initial option in the chapter pathway?',options:['Topical mupirocin','IV vancomycin','Oral fluoroquinolone','Hygiene alone with no treatment'],answer:0,feedback:'Topical therapy is first-line for localized impetigo.',reasoning:'The chapter summary uses topical mupirocin for limited disease and systemic assessment for extensive disease.'},
  {id:'t2',mode:'treatment',chapter:'bacterial',difficulty:'TREATMENT',vignette:'A patient has extensive impetigo with no clear MRSA risk or beta-lactam allergy.',q:'Which common systemic first-line option is listed?',options:['Cephalexin','Acyclovir','Permethrin','Terbinafine'],answer:0,feedback:'Cephalexin is listed as a systemic option for S. aureus and streptococci.',reasoning:'Antibiotic choice still depends on extent, likely pathogens, allergy, MRSA risk, and local resistance.'},
  {id:'t3',mode:'treatment',chapter:'fungal',difficulty:'TREATMENT',vignette:'An adult has uncomplicated localized interdigital tinea pedis.',q:'Which treatment is an appropriate initial choice?',options:['Topical terbinafine or clotrimazole','IV acyclovir','Rifampin monotherapy','Topical mupirocin alone'],answer:0,feedback:'A topical antifungal is appropriate for localized tinea pedis.',reasoning:'The chapter lists topical terbinafine, clotrimazole, or ketoconazole for 2–4 weeks, with systemic therapy for severe or chronic disease.'},
  {id:'t4',mode:'treatment',chapter:'viral',difficulty:'TREATMENT',vignette:'A patient has symptomatic primary HSV-1 infection that began less than 72 hours ago.',q:'Which treatment principle offers the best response?',options:['Start antiviral therapy early','Delay therapy for two weeks','Use an antifungal','Use permethrin'],answer:0,feedback:'Early acyclovir or an alternative antiviral offers the best response.',reasoning:'The chapter emphasizes starting treatment within 72 hours, with IV acyclovir for severe or disseminated disease.'},
  {id:'t5',mode:'treatment',chapter:'parasitic',difficulty:'TREATMENT',vignette:'An adult has classic uncomplicated scabies without immunosuppression.',q:'What is the listed first-line treatment?',options:['Permethrin 5%, repeated after 7 days','Topical acyclovir','Oral cephalexin alone','Clofazimine monotherapy'],answer:0,feedback:'Permethrin 5% is first-line for classic scabies.',reasoning:'Repeat treatment after 7 days and treat contacts while cleaning clothes and bedding to reduce reinfestation.'},
  {id:'t6',mode:'treatment',chapter:'mycobacterial',difficulty:'TREATMENT',vignette:'A patient is diagnosed with multibacillary leprosy.',q:'What is the core treatment principle?',options:['Long-term multidrug therapy','A three-day topical antibiotic','Antiviral monotherapy','No treatment if afebrile'],answer:0,feedback:'Leprosy requires prolonged multidrug therapy.',reasoning:'Multidrug therapy reduces resistance and may include rifampin, dapsone, and clofazimine depending on classification and protocol.'}
 ]
};

const chapterColors={introduction:'#4aa9d8',bacterial:'#f4bd22',fungal:'#6ebd43',viral:'#b052a0',parasitic:'#349ad5',mycobacterial:'#d36a22'};
let currentMode='mcq', currentChapter='all', currentIndex=0, currentList=[], locked=false;
const answers=new Map();

const els={modeSwitch:document.getElementById('modeSwitch'),chapterFilter:document.getElementById('chapterFilter'),modeLabel:document.getElementById('modeLabel'),chapterBadge:document.getElementById('chapterBadge'),difficultyBadge:document.getElementById('difficultyBadge'),caseVignette:document.getElementById('caseVignette'),questionText:document.getElementById('questionText'),options:document.getElementById('labOptions'),feedback:document.getElementById('labFeedback'),feedbackIcon:document.querySelector('#labFeedback span'),feedbackText:document.querySelector('#labFeedback p'),reasoningBox:document.getElementById('reasoningBox'),reasoningText:document.getElementById('reasoningText'),next:document.getElementById('nextBtn'),bar:document.getElementById('practiceBar'),count:document.getElementById('practiceCount'),correct:document.getElementById('correctCount'),answered:document.getElementById('answeredCount'),percent:document.getElementById('scorePercent'),arc:document.getElementById('scoreArc'),reset:document.getElementById('resetBtn'),results:document.getElementById('chapterResults'),total:document.getElementById('questionTotal')};

function getLang(){return window.currentDMLang||'ar'}
function getQuestions(){return questions[getLang()]}
function buildFilters(){
 const lang=getLang(), copy=labCopy[lang];
 const keys=['all','introduction','bacterial','fungal','viral','parasitic','mycobacterial'];
 els.chapterFilter.innerHTML=keys.map(k=>`<button data-chapter="${k}" class="${k===currentChapter?'active':''}">${copy.chapters[k]}</button>`).join('');
 els.chapterFilter.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{currentChapter=b.dataset.chapter;currentIndex=0;buildFilters();refreshList()}));
}
function updateModeButtons(){els.modeSwitch.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.mode===currentMode))}
function refreshList(){
 currentList=getQuestions().filter(q=>q.mode===currentMode&&(currentChapter==='all'||q.chapter===currentChapter));
 if(currentIndex>=currentList.length)currentIndex=0;
 renderQuestion(); updateResults();
}
function renderQuestion(){
 const lang=getLang(),copy=labCopy[lang]; locked=false;
 els.feedback.className='lab-feedback';els.reasoningBox.classList.remove('show');els.next.disabled=true;
 if(!currentList.length){els.modeLabel.textContent=copy.modes[currentMode];els.chapterBadge.textContent='—';els.difficultyBadge.textContent='—';els.caseVignette.className='case-vignette';els.questionText.textContent=copy.empty;els.options.innerHTML='';els.count.textContent='00 / 00';els.bar.style.width='0%';return}
 const q=currentList[currentIndex];
 els.modeLabel.textContent=copy.modes[currentMode];els.chapterBadge.textContent=copy.chapters[q.chapter].toUpperCase();els.chapterBadge.style.background=chapterColors[q.chapter];els.difficultyBadge.textContent=q.difficulty;
 els.caseVignette.textContent=q.vignette||'';els.caseVignette.classList.toggle('show',Boolean(q.vignette));els.questionText.textContent=q.q;els.options.innerHTML='';
 q.options.forEach((o,i)=>{const b=document.createElement('button');b.textContent=o;b.addEventListener('click',()=>choose(i,b,q));els.options.appendChild(b)});
 els.count.textContent=`${String(currentIndex+1).padStart(2,'0')} / ${String(currentList.length).padStart(2,'0')}`;els.bar.style.width=`${((currentIndex+1)/currentList.length)*100}%`;
 const prior=answers.get(q.id);if(prior!==undefined){revealPrior(q,prior)}
}
function choose(i,button,q){if(locked)return;locked=true;answers.set(q.id,i);showAnswer(q,i,button);updateScore();updateResults()}
function revealPrior(q,i){locked=true;const buttons=[...els.options.children];showAnswer(q,i,buttons[i],false)}
function showAnswer(q,i,button,enableNext=true){
 const buttons=[...els.options.children];buttons.forEach((b,idx)=>{b.disabled=true;if(idx===q.answer)b.classList.add('correct')});
 const good=i===q.answer;if(!good&&button)button.classList.add('wrong');
 const copy=labCopy[getLang()];els.feedback.className=`lab-feedback show ${good?'good':'bad'}`;els.feedbackIcon.textContent=good?'✓':'×';els.feedbackText.textContent=`${good?copy.correct:copy.wrong} — ${q.feedback}`;els.reasoningText.textContent=q.reasoning;els.reasoningBox.classList.add('show');els.next.disabled=false;
}
function updateScore(){
 const langQs=getQuestions();let correct=0;answers.forEach((ans,id)=>{const q=langQs.find(x=>x.id===id);if(q&&ans===q.answer)correct++});const answered=answers.size,pct=answered?Math.round(correct/answered*100):0;
 els.correct.textContent=correct;els.answered.textContent=answered;els.percent.textContent=`${pct}%`;els.arc.style.strokeDashoffset=314-(314*pct/100);
}
function updateResults(){
 const lang=getLang(),copy=labCopy[lang],qs=getQuestions(),keys=['introduction','bacterial','fungal','viral','parasitic','mycobacterial'];
 els.results.innerHTML=keys.map(k=>{const set=qs.filter(q=>q.chapter===k),answered=set.filter(q=>answers.has(q.id)),correct=answered.filter(q=>answers.get(q.id)===q.answer).length,pct=answered.length?Math.round(correct/answered.length*100):0;return `<article class="result-card" style="--accent:${chapterColors[k]};--pct:${pct}%"><div><span>${copy.chapters[k].toUpperCase()}</span><b>${pct}%</b></div><i></i><small>${answered.length} / ${set.length} ${copy.resultLabel}</small></article>`}).join('');
}
function nextQuestion(){if(!currentList.length)return;if(currentIndex<currentList.length-1){currentIndex++;renderQuestion()}else{currentIndex=0;renderQuestion();document.getElementById('questionCard').animate([{transform:'scale(.985)'},{transform:'scale(1)'}],{duration:300})}}
function resetAll(){answers.clear();currentIndex=0;updateScore();updateResults();renderQuestion()}
function readParams(){const p=new URLSearchParams(location.search);const mode=p.get('mode'),chapter=p.get('chapter');if(['mcq','case','treatment'].includes(mode))currentMode=mode;if(['introduction','bacterial','fungal','viral','parasitic','mycobacterial'].includes(chapter))currentChapter=chapter}
function initLab(){readParams();els.total.textContent=getQuestions().length;updateModeButtons();buildFilters();refreshList();updateScore();els.modeSwitch.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{currentMode=b.dataset.mode;currentIndex=0;updateModeButtons();refreshList()}));els.next.addEventListener('click',nextQuestion);els.reset.addEventListener('click',resetAll)}
document.addEventListener('DOMContentLoaded',initLab);
window.addEventListener('dm-language-change',()=>{buildFilters();refreshList();updateScore();updateResults()});
